# cloudbuild.yaml — Phase 1 (CI only: build + push)
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _REPO: "kowshal-101018751"
  _IMAGE: "todo-kowshal-101018751"

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/gcp-pipeline-kowshal-101018751/${_REPO}/${_IMAGE}:${SHORT_SHA}'
      - .

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/gcp-pipeline-kowshal-101018751/${_REPO}/${_IMAGE}:${SHORT_SHA}'

images:
  - '${_REGION}-docker.pkg.dev/gcp-pipeline-kowshal-101018751/${_REPO}/${_IMAGE}:${SHORT_SHA}'
